### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by ratancs** [ritiek/trunofficial#13]
For given example

`trunofficial 2024561111`

`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/trunofficial/trunofficial.py", line 148, in __init__
    self.phone = _Phone(phone_parsed)
  File "/usr/local/lib/python3.5/dist-packages/trunofficial/trunofficial.py", line 171, in __init__
    self.national = phone['nationalFormat']
KeyError: 'nationalFormat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/trunofficial", line 11, in <module>
    sys.exit(command_line())
  File "/usr/local/lib/python3.5/dist-packages/trunofficial/trunofficial.py", line 113, in command_line
    owner = search(number, cc=cc)
  File "/usr/local/lib/python3.5/dist-packages/trunofficial/trunofficial.py", line 35, in search
    results = _Attributes(response)
  File "/usr/local/lib/python3.5/dist-packages/trunofficial/trunofficial.py", line 166, in __init__
    six.raise_from(TruecallerError("Cannot find the number in Truecaller database, " + str(self.phone.number) + '.'), None)
AttributeError: '_Attributes' object has no attribute 'phone'
```
`

**Comment by rakave** [comment]
Facing the same error here...

**Comment by ritiek** [comment]
I am not entirely sure but it seems like Truecaller servers are blocking our requests.

**Comment by rakave** [comment]
Could it be because truecaller changed its endpoint from "http://api4.truecaller.com/v1/key" , to  "https://api4.truecaller.com/v1/key"

**Comment by fuzunspm** [comment]
how did you solve this issue?

**Comment by sansmoraxz** [comment]
Umm is the service working?

**Comment by ayushit13** [comment]
is there any solution for above issue ?

**Comment by geekyfox90** [comment]
Any solution ?? or alternative
